; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "AvUpload"
#define MyAppVersion "1.5.0"
#define MyAppExeName "avUpload.exe"
#define MyAppSetupName "avUpload_setup"
#define MyAppPublisher "NASS e.K."
#define MyAppURL "https://www.nass-ek.de"
#define ProgramFiles GetEnv("ProgramFiles")

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{0DBC610A-3C1C-4403-B8CC-071EE32EBF54}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={commonappdata}\{#MyAppName}
DisableDirPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=D:\Dokumente\gpl_de.txt
; Installiert ohne UAC-Prompt in ProgramData - analog zu DHLabel.
PrivilegesRequired=lowest
OutputDir=bin\Release
OutputBaseFilename={#MyAppSetupName}-{#MyAppVersion}
SetupIconFile=D:\Bilder\nass-ek.ico
UninstallDisplayIcon={app}\{#MyAppExeName},0
;Begin adjustments for showing the logo
DisableWelcomePage=False
WizardImageFile=D:\Bilder\wz_nass-ek.bmp
WizardSmallImageFile=D:\Bilder\wz_leer_small.bmp
;End adjustments for showing the logo
Compression=lzma
SolidCompression=yes
WizardStyle=modern
SignTool=Certum

[Languages]
Name: "german"; MessagesFile: "compiler:Languages\German.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}";
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon;
Name: "{usersendto}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon;

[Files]
; Costura.Fody bettet alle verwalteten Abhaengigkeiten in avUpload.exe ein -
; es wird daher nur noch die EXE selbst und ihre Konfigurationsdatei benoetigt.
Source: "bin\Release\avUpload.exe"; DestDir: "{app}"; Flags: confirmoverwrite
Source: "bin\Release\avUpload.exe.config"; DestDir: "{app}"

[Code]

const
  WM_SETTINGCHANGE = $001A;
  SMTO_ABORTIFHUNG = $0002;
  EnvironmentKey   = 'Environment';

function SendMessageTimeout(hWnd: Longint; Msg: Longint; wParam: Longint; lParam: string;
  fuFlags: Longint; uTimeout: Longint; var lpdwResult: Longint): Longint;
  external 'SendMessageTimeoutA@user32.dll stdcall';

{ Haengt Path an die benutzerbezogene PATH-Variable (HKCU) an - keine
  Admin-Rechte noetig, passt zu PrivilegesRequired=lowest. Vermeidet
  Duplikate und benachrichtigt laufende Prozesse per WM_SETTINGCHANGE
  (bereits offene Shells muessen trotzdem neu gestartet werden). }
procedure EnvAddPath(Path: string);
var
  Paths: string;
  BroadcastResult: Longint;
begin
  if not RegQueryStringValue(HKEY_CURRENT_USER, EnvironmentKey, 'Path', Paths) then
    Paths := '';

  if (Paths <> '') and (Pos(';' + Uppercase(Path) + ';', ';' + Uppercase(Paths) + ';') > 0) then
    exit;

  if (Paths <> '') and (Paths[Length(Paths)] <> ';') then
    Paths := Paths + ';';
  Paths := Paths + Path;

  if RegWriteStringValue(HKEY_CURRENT_USER, EnvironmentKey, 'Path', Paths) then
    SendMessageTimeout(HWND_BROADCAST, WM_SETTINGCHANGE, 0, EnvironmentKey, SMTO_ABORTIFHUNG, 5000, BroadcastResult)
  else
    Log('EnvAddPath: Schreiben von HKCU\Environment\Path fehlgeschlagen.');
end;

{ Entfernt genau den Path-Eintrag wieder, den EnvAddPath hinzugefuegt hat. }
procedure EnvRemovePath(Path: string);
var
  Paths: string;
  P: Integer;
  BroadcastResult: Longint;
begin
  if not RegQueryStringValue(HKEY_CURRENT_USER, EnvironmentKey, 'Path', Paths) then
    exit;

  P := Pos(';' + Uppercase(Path) + ';', ';' + Uppercase(Paths) + ';');
  if P = 0 then
    exit;

  { P ist 1-basiert auf dem mit ';' gerahmten String - auf Paths umrechnen. }
  Delete(Paths, P, Length(Path) + 1);
  if (Paths <> '') and (Paths[1] = ';') then
    Delete(Paths, 1, 1);

  if RegWriteStringValue(HKEY_CURRENT_USER, EnvironmentKey, 'Path', Paths) then
    SendMessageTimeout(HWND_BROADCAST, WM_SETTINGCHANGE, 0, EnvironmentKey, SMTO_ABORTIFHUNG, 5000, BroadcastResult)
  else
    Log('EnvRemovePath: Schreiben von HKCU\Environment\Path fehlgeschlagen.');
end;

function GetUninstallString(): String;
var
  sUnInstPath: String;
  sUnInstallString: String;
begin
  sUnInstPath := ExpandConstant('Software\Microsoft\Windows\CurrentVersion\Uninstall\{#emit SetupSetting("AppId")}_is1');
  sUnInstallString := '';
  if not RegQueryStringValue(HKLM, sUnInstPath, 'UninstallString', sUnInstallString) then
    RegQueryStringValue(HKCU, sUnInstPath, 'UninstallString', sUnInstallString);
  Result := sUnInstallString;
end;


{ ///////////////////////////////////////////////////////////////////// }
function IsUpgrade(): Boolean;
begin
  Result := (GetUninstallString() <> '');
end;


{ ///////////////////////////////////////////////////////////////////// }
function UnInstallOldVersion(): Integer;
var
  sUnInstallString: String;
  iResultCode: Integer;
begin
{ Return Values: }
{ 1 - uninstall string is empty }
{ 2 - error executing the UnInstallString }
{ 3 - successfully executed the UnInstallString }

  { default return value }
  Result := 0;

  { get the uninstall string of the old app }
  sUnInstallString := GetUninstallString();
  if sUnInstallString <> '' then begin
    sUnInstallString := RemoveQuotes(sUnInstallString);
    if Exec(sUnInstallString, '/SILENT /NORESTART /SUPPRESSMSGBOXES','', SW_HIDE, ewWaitUntilTerminated, iResultCode) then
      Result := 3
    else
      Result := 2;
  end else
    Result := 1;
end;

{ ///////////////////////////////////////////////////////////////////// }
procedure CurStepChanged(CurStep: TSetupStep);
begin
  if (CurStep=ssInstall) then
  begin
    if (IsUpgrade()) then
    begin
      UnInstallOldVersion();
    end;
  end;

  if (CurStep=ssPostInstall) then
  begin
    EnvAddPath(ExpandConstant('{app}'));
  end;
end;

{ ///////////////////////////////////////////////////////////////////// }
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if (CurUninstallStep=usPostUninstall) then
  begin
    EnvRemovePath(ExpandConstant('{app}'));
  end;
end;
